/icp_localization:
  ros__parameters:
    pcd_file_path: "/home/zcf/Downloads/icp-localization-ros2/ros2_ws/icp_localization_ros2/config/plane_noisy.pcd"
    
    icp_localization_ros2:
      range_data_topic: "/livox/lidar"
      num_accumulated_range_data: 1
      imu_data_topic: "/livox/imu"
      odometry_data_topic: "/Odometry"
      is_use_odometry: true
      is_provide_odom_frame: true
      gravity_vector_filter_time_constant: 0.01
      fixed_frame: "map"
      min_num_odom_msgs_before_ready: 5

    initial_pose:
      x: 0.0 
      y: 0.0 
      z: 0.0 
      roll: 0.0  # degrees  
      pitch: 0.0 # degrees
      yaw: 0.0  # degrees

    calibration:
      imu_to_range_sensor:
        x: -0.041
        y: 0.034
        z: -0.057
        roll: 3.14159
        pitch: 0.0
        yaw: -2.79253

    odometry_source_to_range_sensor:
      x: -0.076
      y: -0.024
      z: 0.034
      roll: 0.0
      pitch: 0.0
      yaw: 0.0 
